### ISSUE TITLE
Adding new purple style for site

### ISSUE THREAD

**Issue by An0nX** [mmmray/xray-online#5]
![изображение](https://github.com/user-attachments/assets/22553033-7af6-49e1-922f-d1b772ab095f)

Here's CSS:
```css
* {
    box-sizing: border-box;
}
html, body {
    height: 100%;
    padding: 0;
    margin: 0;
    display: flex;
    flex-direction: column;
    font-family: 'Open Sans', sans-serif;
    background-color: #1a1a1d;
    color: #e0e0e0;
}

.container {
    width: 100%;
    flex: 1;
    display: flex;
    flex-direction: column;
    max-width: 800px;
    margin: 0 auto;
    padding: 20px;
}

#editor {
    flex: 1;
    border-radius: 8px;
    border: 2px solid #bb86fc;
    height: 500px;
    background-color: #2c2c34;
    color: #e0e0e0;
    padding: 15px;
}

#output {
    padding: 15px;
    line-height: 1.4;
    margin-top: 20px;
    border-radius: 8px;
    border: 2px solid #bb86fc;
    background-color: #2c2c34;
    color: #e0e0e0;
    max-height: 200px;
    overflow-y: auto;
    flex-shrink: 0;
    text-align: center;
}

#output[data-status="ok"] {
    background-color: #d4edda;
    color: #155724;
}

#output[data-status="error"] {
    background-color: #f8d7da;
    color: #721c24;
}

#output[data-status="warn"] {
    background-color: #fff3cd;
    color: #856404;
}

#nav {
    text-align: right;
    margin-bottom: 20px;
}

h1 {
    font-size: 2rem;
    font-weight: 500;
    color: #bb86fc;
    text-align: center;
}

a {
    color: #bb86fc;
}

.cool-color {
    background-image: linear-gradient(to right, #E70000, #FF8C00, #FFEF00, #00811F, #0044FF, #760089);
    -webkit-background-clip: text;
    color: transparent;
}

footer {
    background-color: #202024;
    color: #e0e0e0;
    text-align: center;
    padding: 15px;
    position: fixed;
    bottom: 0;
    width: 100%;
}

button {
    background-color: #6200ee;
    color: #ffffff;
    border: none;
    padding: 10px 20px;
    border-radius: 8px;
    cursor: pointer;
}

button:hover {
    background-color: #3700b3;
}
```
